### ISSUE TITLE
swift lint for for unwrapping

### ISSUE THREAD

**Issue by SentulAsia** [zaimramlan/clean-swift-template#4]
to add this to routes template:
```
// swiftlint:disable force_unwrapping
passData(to: &destinationDS, from: dataStore!)
// swiftlint:enable force_unwrapping
```

**Comment by SentulAsia** [comment]
maybe can consider add it at main routes func as well as we are force cast the ViewController there...

**Comment by zaimramlan** [comment]
Good suggestion @SentulAsia , but since the template is open to everyone, we wouldn't want to couple the linter implementation into the template itself, especially when different teams may use different Swift linter tools/services.

Specifically to SwiftLint, it's possible to prevent a rule, from checking a certain matching file, as mentioned in their [README](https://github.com/realm/SwiftLint#configuration).

Closing this issue, as each teams can use their own Swift linter tools/services, to filter which files to skip the checking.
